name: SkiRT_coarse_rp_felice_004
coarse_name: SkiRT_coarse_rp_felice_004
dataset_type: resynth
mode: train
outfit: rp_felice_posed_004

batch_size: 8
lr: 3e-4
lr_geomfeat: 5e-4

epochs: 150
save_every: 10