name: SkiRT_coarse_rp_christine_027
coarse_name: SkiRT_coarse_rp_christine_027
dataset_type: resynth
mode: train
outfit: rp_christine_posed_027

batch_size: 8
lr: 3e-4
lr_geomfeat: 5e-4

epochs: 150
save_every: 10